import type { CandidatePoolProfile } from "@/sms-engine/graph/candidateRetrieval";
import type { RelationshipGraphEdge } from "@/sms-engine/graph/relationshipProximity";

export type MatchingEvalCandidate = CandidatePoolProfile & {
  expectedMatchingBehaviorNotes: string[];
};

function c(input: Partial<MatchingEvalCandidate> & { id: string; displayName: string }): MatchingEvalCandidate {
  return {
    id: input.id,
    personId: input.personId === undefined ? `person-${input.id}` : input.personId,
    creatorProfileId: input.creatorProfileId ?? null,
    contactId: input.contactId ?? null,
    talentCandidateId: input.talentCandidateId ?? null,
    candidateRecommendationId: input.candidateRecommendationId ?? null,
    publicWebResearchResultId: input.publicWebResearchResultId ?? null,
    displayName: input.displayName,
    roleTags: input.roleTags || ["host"],
    skillTags: input.skillTags || input.roleTags || ["host"],
    fandomTags: input.fandomTags || ["anime"],
    communityTags: input.communityTags || [],
    city: input.city ?? "Los Angeles",
    metro: input.metro ?? "Los Angeles",
    locationConfidence: input.locationConfidence ?? 0.85,
    reviewStatus: input.reviewStatus || "APPROVED_FOR_INTERNAL_REVIEW",
    sourceMode: input.sourceMode || "INTERNAL_DB",
    evidenceQualityScore: input.evidenceQualityScore ?? 82,
    contactabilityScore: input.contactabilityScore ?? 70,
    contactabilityRisk: input.contactabilityRisk,
    recommendedContactPathForAdminReview:
      input.recommendedContactPathForAdminReview ?? "internal_contact",
    doNotContact: input.doNotContact ?? false,
    optedOut: input.optedOut ?? false,
    expectedMatchingBehaviorNotes: input.expectedMatchingBehaviorNotes || [],
  };
}

export const matchingEvalCandidates: MatchingEvalCandidate[] = [
  c({
    id: "candidate-la-anime-photo-direct",
    personId: "person-la-anime-photo-direct",
    displayName: "Fixture LA Anime Photo Direct",
    roleTags: ["photographer", "cosplay photographer"],
    skillTags: ["photography", "cosplay photographer"],
    fandomTags: ["anime", "cosplay"],
    evidenceQualityScore: 95,
    contactabilityScore: 92,
    contactabilityRisk: "LOW",
    expectedMatchingBehaviorNotes: ["strong internal direct relationship candidate"],
  }),
  c({
    id: "candidate-la-anime-photo-approved",
    personId: "person-la-anime-photo-approved",
    displayName: "Fixture LA Anime Photo Approved",
    roleTags: ["photographer", "cosplay photographer"],
    skillTags: ["photography"],
    fandomTags: ["anime", "cosplay"],
    evidenceQualityScore: 94,
    contactabilityScore: 88,
    reviewStatus: "APPROVED_FOR_SHORTLIST",
  }),
  c({
    id: "candidate-public-la-photo-reviewed",
    personId: null,
    publicWebResearchResultId: "pwr-la-photo-reviewed",
    displayName: "Fixture Public LA Photo Reviewed",
    roleTags: ["photographer", "cosplay photographer"],
    skillTags: ["photography"],
    fandomTags: ["anime", "cosplay"],
    sourceMode: "PUBLIC_WEB_RESEARCH",
    reviewStatus: "APPROVED_FOR_INTERNAL_REVIEW",
    evidenceQualityScore: 98,
    contactabilityScore: 76,
    recommendedContactPathForAdminReview: "public_contact_form_reviewed",
    expectedMatchingBehaviorNotes: ["can rank if evidence is strong but should remain review-gated"],
  }),
  c({
    id: "candidate-public-la-photo-unreviewed",
    personId: null,
    publicWebResearchResultId: "pwr-la-photo-unreviewed",
    displayName: "Fixture Public LA Photo Unreviewed",
    roleTags: ["photographer", "cosplay photographer"],
    skillTags: ["photography"],
    fandomTags: ["anime", "cosplay"],
    sourceMode: "PUBLIC_WEB_RESEARCH",
    reviewStatus: "NEEDS_QUALITY_REVIEW",
    evidenceQualityScore: 99,
    contactabilityScore: 70,
    expectedMatchingBehaviorNotes: ["should be held back by public-web review gate"],
  }),
  c({
    id: "candidate-nyc-cosplayer-direct",
    personId: "person-nyc-cosplayer-direct",
    displayName: "Fixture NYC Cosplayer Direct",
    roleTags: ["cosplayer", "host"],
    skillTags: ["cosplayer", "performance", "host"],
    fandomTags: ["anime", "cosplay"],
    communityTags: ["maid cafe"],
    city: "New York City",
    metro: "New York City",
    evidenceQualityScore: 91,
    contactabilityScore: 86,
  }),
  c({
    id: "candidate-nyc-cafe-venue",
    personId: "person-nyc-cafe-venue",
    displayName: "Fixture NYC Cafe Venue",
    roleTags: ["venue owner", "venue contact"],
    skillTags: ["venue owner", "cafe partner"],
    fandomTags: ["anime"],
    communityTags: ["maid cafe"],
    city: "New York City",
    metro: "New York City",
    evidenceQualityScore: 88,
    contactabilityScore: 90,
  }),
  c({
    id: "candidate-atl-gaming-host",
    personId: "person-atl-gaming-host",
    displayName: "Fixture ATL Gaming Host",
    roleTags: ["host", "game demo host"],
    skillTags: ["host", "game demo host"],
    fandomTags: ["gaming", "anime-adjacent gaming"],
    communityTags: ["local gaming"],
    city: "Atlanta",
    metro: "Atlanta",
    evidenceQualityScore: 87,
    contactabilityScore: 82,
  }),
  c({
    id: "candidate-atl-vendor-coordinator",
    personId: "person-atl-vendor-coordinator",
    displayName: "Fixture ATL Vendor Coordinator",
    roleTags: ["vendor coordinator", "production assistant"],
    skillTags: ["vendor coordinator", "production assistant"],
    fandomTags: ["gaming"],
    city: "Atlanta",
    metro: "Atlanta",
    evidenceQualityScore: 83,
    contactabilityScore: 78,
  }),
  c({
    id: "candidate-la-maid-performer",
    personId: "person-la-maid-performer",
    displayName: "Fixture LA Maid Performer",
    roleTags: ["maid cafe performer", "host"],
    skillTags: ["maid cafe performer", "performance", "host"],
    fandomTags: ["anime", "maid cafe"],
    communityTags: ["cosplay", "performance"],
    evidenceQualityScore: 90,
    contactabilityScore: 82,
  }),
  c({
    id: "candidate-la-maid-host-mutual",
    personId: "person-la-maid-host-mutual",
    displayName: "Fixture LA Maid Host Referral",
    roleTags: ["host", "maid cafe performer"],
    skillTags: ["host", "performance"],
    fandomTags: ["anime", "maid cafe"],
    evidenceQualityScore: 84,
    contactabilityScore: 80,
  }),
  c({
    id: "candidate-la-artist-illustrator",
    personId: "person-la-artist-illustrator",
    displayName: "Fixture LA Artist Illustrator",
    roleTags: ["illustrator", "artist alley"],
    skillTags: ["illustrator", "artist alley"],
    fandomTags: ["anime"],
    communityTags: ["artist alley", "convention vendor"],
    evidenceQualityScore: 92,
    contactabilityScore: 84,
  }),
  c({
    id: "candidate-remote-illustrator-approved",
    personId: "person-remote-illustrator-approved",
    displayName: "Fixture Remote Illustrator Approved",
    roleTags: ["illustrator", "graphic designer"],
    skillTags: ["illustrator", "graphic designer", "designer"],
    fandomTags: ["anime", "Jujutsu Kaisen"],
    communityTags: ["artist alley"],
    city: "Remote",
    metro: null,
    evidenceQualityScore: 96,
    contactabilityScore: 79,
    reviewStatus: "APPROVED_FOR_SHORTLIST",
    expectedMatchingBehaviorNotes: ["should rank for remote-friendly design needs despite location mismatch"],
  }),
  c({
    id: "candidate-la-dj-direct",
    personId: "person-la-dj-direct",
    displayName: "Fixture LA DJ Direct",
    roleTags: ["DJ"],
    skillTags: ["DJ", "anime rave dj"],
    fandomTags: ["anime"],
    communityTags: ["music", "performance"],
    evidenceQualityScore: 90,
    contactabilityScore: 84,
  }),
  c({
    id: "candidate-la-venue-owner",
    personId: "person-la-venue-owner",
    displayName: "Fixture LA Venue Owner",
    roleTags: ["venue owner", "venue contact"],
    skillTags: ["venue owner"],
    fandomTags: ["creative community"],
    city: "Los Angeles",
    metro: "Los Angeles",
    evidenceQualityScore: 86,
    contactabilityScore: 88,
  }),
  c({
    id: "candidate-nyc-venue-owner",
    personId: "person-nyc-venue-owner",
    displayName: "Fixture NYC Venue Owner",
    roleTags: ["venue owner", "venue contact"],
    skillTags: ["venue owner"],
    city: "New York City",
    metro: "New York City",
    evidenceQualityScore: 85,
    contactabilityScore: 86,
    expectedMatchingBehaviorNotes: ["should rank low for LA local-required venue roles"],
  }),
  c({
    id: "candidate-la-content-creator",
    personId: "person-la-content-creator",
    displayName: "Fixture LA Content Creator",
    roleTags: ["social content creator", "content creator"],
    skillTags: ["social content creator", "content capture"],
    fandomTags: ["anime", "creative community"],
    communityTags: ["brand"],
    evidenceQualityScore: 88,
    contactabilityScore: 74,
  }),
  c({
    id: "candidate-la-brand-host",
    personId: "person-la-brand-host",
    displayName: "Fixture LA Brand Host",
    roleTags: ["host", "community host"],
    skillTags: ["host", "brand host"],
    fandomTags: ["creative community"],
    communityTags: ["brand"],
    evidenceQualityScore: 83,
    contactabilityScore: 77,
  }),
  c({
    id: "candidate-nyc-cosplay-photo",
    personId: "person-nyc-cosplay-photo",
    displayName: "Fixture NYC Cosplay Photo",
    roleTags: ["photographer", "cosplay photographer"],
    skillTags: ["photography", "cosplay photographer"],
    fandomTags: ["anime", "cosplay"],
    city: "New York City",
    metro: "New York City",
    evidenceQualityScore: 93,
    contactabilityScore: 83,
  }),
  c({
    id: "candidate-nyc-production-assistant",
    personId: "person-nyc-production-assistant",
    displayName: "Fixture NYC Production Assistant",
    roleTags: ["production assistant", "volunteer coordinator"],
    skillTags: ["production assistant", "volunteer coordinator"],
    fandomTags: ["anime"],
    city: "New York City",
    metro: "New York City",
    evidenceQualityScore: 78,
    contactabilityScore: 73,
  }),
  c({
    id: "candidate-la-production-assistant",
    personId: "person-la-production-assistant",
    displayName: "Fixture LA Production Assistant",
    roleTags: ["production assistant", "volunteer coordinator"],
    skillTags: ["production assistant", "volunteer coordinator"],
    fandomTags: ["anime"],
    city: "Los Angeles",
    metro: "Los Angeles",
    evidenceQualityScore: 80,
    contactabilityScore: 76,
  }),
  c({
    id: "candidate-la-volunteer-coordinator",
    personId: "person-la-volunteer-coordinator",
    displayName: "Fixture LA Volunteer Coordinator",
    roleTags: ["volunteer coordinator", "production coordinator"],
    skillTags: ["volunteer coordinator", "production coordinator"],
    fandomTags: ["anime"],
    evidenceQualityScore: 82,
    contactabilityScore: 75,
  }),
  c({
    id: "candidate-la-production-coordinator",
    personId: "person-la-production-coordinator",
    displayName: "Fixture LA Production Coordinator",
    roleTags: ["production coordinator", "production assistant"],
    skillTags: ["production coordinator", "logistics"],
    fandomTags: ["anime"],
    evidenceQualityScore: 89,
    contactabilityScore: 82,
  }),
  c({
    id: "candidate-la-security-logistics",
    personId: "person-la-security-logistics",
    displayName: "Fixture LA Safety Logistics",
    roleTags: ["production coordinator", "venue owner"],
    skillTags: ["production coordinator", "safety logistics", "venue owner"],
    fandomTags: ["anime"],
    evidenceQualityScore: 91,
    contactabilityScore: 86,
  }),
  c({
    id: "candidate-love-deepspace-host",
    personId: "person-love-deepspace-host",
    displayName: "Fixture Love Deepspace Host",
    roleTags: ["host", "community host"],
    skillTags: ["host"],
    fandomTags: ["Love and Deepspace"],
    communityTags: ["otome game", "anime-adjacent gaming"],
    evidenceQualityScore: 88,
    contactabilityScore: 80,
  }),
  c({
    id: "candidate-casual-host",
    personId: "person-casual-host",
    displayName: "Fixture Casual Meetup Host",
    roleTags: ["host", "community host"],
    skillTags: ["host"],
    fandomTags: ["anime"],
    communityTags: ["community meetup"],
    evidenceQualityScore: 84,
    contactabilityScore: 72,
  }),
  c({
    id: "candidate-weak-evidence-photo",
    personId: "person-weak-evidence-photo",
    displayName: "Fixture Weak Evidence Photo",
    roleTags: ["photographer"],
    skillTags: ["photography"],
    fandomTags: ["anime"],
    evidenceQualityScore: 22,
    contactabilityScore: 60,
    expectedMatchingBehaviorNotes: ["weak evidence should lower confidence"],
  }),
  c({
    id: "candidate-no-contact-photo",
    personId: "person-no-contact-photo",
    displayName: "Fixture No Contact Photo",
    roleTags: ["photographer"],
    skillTags: ["photography"],
    fandomTags: ["anime"],
    evidenceQualityScore: 80,
    contactabilityScore: 0,
    recommendedContactPathForAdminReview: null,
    expectedMatchingBehaviorNotes: ["no contactability should lower operational score"],
  }),
  c({
    id: "candidate-public-phone-contact",
    personId: null,
    publicWebResearchResultId: "pwr-public-phone-contact",
    displayName: "Fixture Public Phone Contact",
    roleTags: ["photographer"],
    skillTags: ["photography"],
    sourceMode: "PUBLIC_WEB_RESEARCH",
    reviewStatus: "APPROVED_FOR_INTERNAL_REVIEW",
    evidenceQualityScore: 84,
    contactabilityScore: 55,
    contactabilityRisk: "HIGH",
    recommendedContactPathForAdminReview: "public_business_phone_requires_review",
  }),
  c({
    id: "candidate-opted-out",
    personId: "person-opted-out",
    displayName: "Fixture Opted Out",
    roleTags: ["photographer", "DJ", "host"],
    skillTags: ["photography", "DJ", "host"],
    evidenceQualityScore: 100,
    contactabilityScore: 100,
    optedOut: true,
  }),
  c({
    id: "candidate-do-not-contact",
    personId: "person-do-not-contact",
    displayName: "Fixture Do Not Contact",
    roleTags: ["photographer", "DJ", "host"],
    skillTags: ["photography", "DJ", "host"],
    evidenceQualityScore: 100,
    contactabilityScore: 100,
    doNotContact: true,
    reviewStatus: "DO_NOT_CONTACT",
  }),
  c({
    id: "candidate-duplicate-public",
    personId: null,
    publicWebResearchResultId: "pwr-duplicate-public",
    displayName: "Fixture Duplicate Public",
    roleTags: ["photographer"],
    skillTags: ["photography"],
    sourceMode: "PUBLIC_WEB_RESEARCH",
    reviewStatus: "DUPLICATE",
    evidenceQualityScore: 90,
    contactabilityScore: 80,
  }),
  c({
    id: "candidate-sf-designer",
    personId: "person-sf-designer",
    displayName: "Fixture SF Designer",
    roleTags: ["graphic designer", "illustrator"],
    skillTags: ["graphic designer", "designer", "illustrator"],
    fandomTags: ["anime"],
    city: "San Francisco",
    metro: "Bay Area",
    evidenceQualityScore: 90,
    contactabilityScore: 78,
  }),
  c({
    id: "candidate-atl-photographer",
    personId: "person-atl-photographer",
    displayName: "Fixture ATL Photographer",
    roleTags: ["photographer"],
    skillTags: ["photography"],
    fandomTags: ["gaming"],
    city: "Atlanta",
    metro: "Atlanta",
    evidenceQualityScore: 86,
    contactabilityScore: 80,
  }),
  c({
    id: "candidate-atl-production-assistant",
    personId: "person-atl-production-assistant",
    displayName: "Fixture ATL Production Assistant",
    roleTags: ["production assistant"],
    skillTags: ["production assistant"],
    fandomTags: ["gaming"],
    city: "Atlanta",
    metro: "Atlanta",
    evidenceQualityScore: 79,
    contactabilityScore: 72,
  }),
  c({
    id: "candidate-la-videographer",
    personId: "person-la-videographer",
    displayName: "Fixture LA Videographer",
    roleTags: ["videographer", "photographer"],
    skillTags: ["videographer", "photography"],
    fandomTags: ["anime"],
    evidenceQualityScore: 83,
    contactabilityScore: 75,
  }),
  c({
    id: "candidate-la-stylist",
    personId: "person-la-stylist",
    displayName: "Fixture LA Stylist",
    roleTags: ["stylist", "MUA"],
    skillTags: ["stylist", "MUA"],
    fandomTags: ["cosplay"],
    evidenceQualityScore: 78,
    contactabilityScore: 70,
  }),
  c({
    id: "candidate-nyc-stylist",
    personId: "person-nyc-stylist",
    displayName: "Fixture NYC Stylist",
    roleTags: ["stylist", "MUA"],
    skillTags: ["stylist", "MUA"],
    fandomTags: ["cosplay"],
    city: "New York City",
    metro: "New York City",
    evidenceQualityScore: 82,
    contactabilityScore: 76,
  }),
  c({
    id: "candidate-la-vendor-coordinator",
    personId: "person-la-vendor-coordinator",
    displayName: "Fixture LA Vendor Coordinator",
    roleTags: ["vendor coordinator", "production coordinator"],
    skillTags: ["vendor coordinator"],
    fandomTags: ["artist alley", "anime"],
    communityTags: ["convention vendor"],
    evidenceQualityScore: 84,
    contactabilityScore: 80,
  }),
  c({
    id: "candidate-public-illustrator-reviewed",
    personId: null,
    publicWebResearchResultId: "pwr-illustrator-reviewed",
    displayName: "Fixture Public Illustrator Reviewed",
    roleTags: ["illustrator", "artist alley"],
    skillTags: ["illustrator"],
    fandomTags: ["anime"],
    communityTags: ["artist alley"],
    sourceMode: "PUBLIC_WEB_RESEARCH",
    reviewStatus: "APPROVED_FOR_INTERNAL_REVIEW",
    evidenceQualityScore: 97,
    contactabilityScore: 74,
  }),
  c({
    id: "candidate-public-ambiguous",
    personId: null,
    publicWebResearchResultId: "pwr-public-ambiguous",
    displayName: "Fixture Public Ambiguous",
    roleTags: ["host"],
    skillTags: ["host"],
    sourceMode: "PUBLIC_WEB_RESEARCH",
    reviewStatus: "NEEDS_IDENTITY_REVIEW",
    evidenceQualityScore: 65,
    contactabilityScore: 50,
  }),
  c({
    id: "candidate-internal-pending-host",
    personId: "person-internal-pending-host",
    displayName: "Fixture Pending Host",
    roleTags: ["host"],
    skillTags: ["host"],
    fandomTags: ["anime"],
    reviewStatus: "DISCOVERED",
    evidenceQualityScore: 70,
    contactabilityScore: 65,
  }),
  c({
    id: "candidate-la-social-creator-public-reviewed",
    personId: null,
    publicWebResearchResultId: "pwr-social-reviewed",
    displayName: "Fixture Public Social Creator Reviewed",
    roleTags: ["social content creator", "content creator"],
    skillTags: ["social content creator"],
    fandomTags: ["anime", "creative community"],
    sourceMode: "PUBLIC_WEB_RESEARCH",
    reviewStatus: "APPROVED_FOR_INTERNAL_REVIEW",
    evidenceQualityScore: 93,
    contactabilityScore: 72,
  }),
  c({
    id: "candidate-la-community-host",
    personId: "person-la-community-host",
    displayName: "Fixture LA Community Host",
    roleTags: ["host", "community host"],
    skillTags: ["host", "community host"],
    fandomTags: ["anime", "cosplay"],
    communityTags: ["community meetup"],
    evidenceQualityScore: 86,
    contactabilityScore: 79,
  }),
  c({
    id: "candidate-nyc-photographer-public-reviewed",
    personId: null,
    publicWebResearchResultId: "pwr-nyc-photo-reviewed",
    displayName: "Fixture Public NYC Photographer Reviewed",
    roleTags: ["photographer", "cosplay photographer"],
    skillTags: ["photography"],
    fandomTags: ["anime", "cosplay"],
    city: "New York City",
    metro: "New York City",
    sourceMode: "PUBLIC_WEB_RESEARCH",
    reviewStatus: "APPROVED_FOR_INTERNAL_REVIEW",
    evidenceQualityScore: 96,
    contactabilityScore: 76,
  }),
];

export const matchingEvalRelationshipEdges: RelationshipGraphEdge[] = [
  {
    fromEntityType: "PERSON",
    fromEntityId: "requester-la-anime",
    toEntityType: "PERSON",
    toEntityId: "person-la-anime-photo-direct",
    edgeType: "WORKED_TOGETHER",
    strength: 0.95,
    confidence: 0.95,
    sourceType: "INTERNAL_DB",
    isInferred: false,
  },
  {
    fromEntityType: "PERSON",
    fromEntityId: "requester-la-anime",
    toEntityType: "PERSON",
    toEntityId: "person-la-community-host",
    edgeType: "SAME_EVENT",
    strength: 0.75,
    confidence: 0.85,
    sourceType: "INTERNAL_DB",
    isInferred: false,
  },
  {
    fromEntityType: "PERSON",
    fromEntityId: "requester-nyc-cosplay",
    toEntityType: "PERSON",
    toEntityId: "person-nyc-cosplayer-direct",
    edgeType: "FRIEND",
    strength: 0.9,
    confidence: 0.92,
    sourceType: "INTERNAL_DB",
    isInferred: false,
  },
  {
    fromEntityType: "PERSON",
    fromEntityId: "requester-la-maid",
    toEntityType: "PERSON",
    toEntityId: "person-mutual-bridge-la-maid",
    edgeType: "FRIEND",
    strength: 0.8,
    confidence: 0.9,
    sourceType: "INTERNAL_DB",
    isInferred: false,
  },
  {
    fromEntityType: "PERSON",
    fromEntityId: "person-mutual-bridge-la-maid",
    toEntityType: "PERSON",
    toEntityId: "person-la-maid-host-mutual",
    edgeType: "REFERRED_BY",
    strength: 0.78,
    confidence: 0.86,
    sourceType: "INTERNAL_DB",
    isInferred: false,
  },
  {
    fromEntityType: "PERSON",
    fromEntityId: "requester-la-rave",
    toEntityType: "PERSON",
    toEntityId: "person-la-dj-direct",
    edgeType: "WORKED_TOGETHER",
    strength: 0.92,
    confidence: 0.93,
    sourceType: "INTERNAL_DB",
    isInferred: false,
  },
  {
    fromEntityType: "PERSON",
    fromEntityId: "requester-la-design",
    toEntityType: "PERSON",
    toEntityId: "person-remote-illustrator-approved",
    edgeType: "REFERRED_BY",
    strength: 0.72,
    confidence: 0.84,
    sourceType: "INTERNAL_DB",
    isInferred: false,
  },
];
